### ISSUE TITLE
metaclass error for chapter7

### ISSUE THREAD

**Issue by jinay1991** [mbeyeler/opencv-python-blueprints#17]
When I ran code on Mac OS 10.12.3 with Python 2.7 I received following error for chapter7.py

```
bash-3.2$ python chapter7.py
Traceback (most recent call last):
  File "chapter7.py", line 33, in <module>
    from gui import BaseLayout
  File "/Users/jinay/workspace/upwork/opencv-python-blueprints/chapter7/gui.py", line 20, in <module>
    class BaseLayout(Meta1):
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/abc.py", line 87, in new
    cls = super(ABCMeta, mcls).__new__(mcls, name, bases, namespace)
TypeError: Error when calling the metaclass bases
    metaclass conflict: the metaclass of a derived class must be a (non-strict) subclass of the metaclasses of all its bases
```

Possible work around could be #16

**Comment by mbeyeler** [comment]
Closed #17 via https://github.com/mbeyeler/opencv-python-blueprints/commit/68330f640f0e9ed27069cfb7e2c52b9b05254f46.
