### ISSUE TITLE
Chapter 2 

### ISSUE THREAD

**Issue by cjsumne** [mbeyeler/opencv-python-blueprints#19]
Hi, I am trying to understand your code but keep getting an error that I can't quite get around.

I keep getting this error and I 
user:~/opencv-python-blueprints/chapter2$ python chapter2.py 
Could not open audio: -1
Traceback (most recent call last):
  File "chapter2.py", line 93, in <module>
    main()
  File "chapter2.py", line 87, in main
    layout = KinectLayout(None, -1, 'Kinect Hand Gesture Recognition', capture)
  File "/home/lpcs/opencv-python-blueprints/chapter2/gui.py", line 71, in __init__
    self.bmp = wx.BitmapFromBuffer(self.imgWidth, self.imgHeight, frame)
  File "/usr/lib/python2.7/dist-packages/wx-2.8-gtk2-unicode/wx/_gdi.py", line 856, in BitmapFromBuffer
    return _gdi_._BitmapFromBuffer(width, height, dataBuffer)
ValueError: Invalid data buffer size.

**Comment by rlabuguen** [comment]
Getting also the same error. Please advise..
